/* tslint:disable */
/* eslint-disable */
/**
 * go_load/v1/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RpcStatus } from './RpcStatus';
import {
    RpcStatusFromJSON,
    RpcStatusFromJSONTyped,
    RpcStatusToJSON,
} from './RpcStatus';
import type { V1GetDownloadTaskFileResponse } from './V1GetDownloadTaskFileResponse';
import {
    V1GetDownloadTaskFileResponseFromJSON,
    V1GetDownloadTaskFileResponseFromJSONTyped,
    V1GetDownloadTaskFileResponseToJSON,
} from './V1GetDownloadTaskFileResponse';

/**
 * 
 * @export
 * @interface StreamResultOfV1GetDownloadTaskFileResponse
 */
export interface StreamResultOfV1GetDownloadTaskFileResponse {
    /**
     * 
     * @type {V1GetDownloadTaskFileResponse}
     * @memberof StreamResultOfV1GetDownloadTaskFileResponse
     */
    result?: V1GetDownloadTaskFileResponse;
    /**
     * 
     * @type {RpcStatus}
     * @memberof StreamResultOfV1GetDownloadTaskFileResponse
     */
    error?: RpcStatus;
}

/**
 * Check if a given object implements the StreamResultOfV1GetDownloadTaskFileResponse interface.
 */
export function instanceOfStreamResultOfV1GetDownloadTaskFileResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StreamResultOfV1GetDownloadTaskFileResponseFromJSON(json: any): StreamResultOfV1GetDownloadTaskFileResponse {
    return StreamResultOfV1GetDownloadTaskFileResponseFromJSONTyped(json, false);
}

export function StreamResultOfV1GetDownloadTaskFileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreamResultOfV1GetDownloadTaskFileResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : V1GetDownloadTaskFileResponseFromJSON(json['result']),
        'error': !exists(json, 'error') ? undefined : RpcStatusFromJSON(json['error']),
    };
}

export function StreamResultOfV1GetDownloadTaskFileResponseToJSON(value?: StreamResultOfV1GetDownloadTaskFileResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': V1GetDownloadTaskFileResponseToJSON(value.result),
        'error': RpcStatusToJSON(value.error),
    };
}

