/* tslint:disable */
/* eslint-disable */
/**
 * go_load/v1/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1Account
 */
export interface V1Account {
    /**
     * 
     * @type {string}
     * @memberof V1Account
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Account
     */
    accountName?: string;
}

/**
 * Check if a given object implements the V1Account interface.
 */
export function instanceOfV1Account(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1AccountFromJSON(json: any): V1Account {
    return V1AccountFromJSONTyped(json, false);
}

export function V1AccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Account {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'accountName': !exists(json, 'accountName') ? undefined : json['accountName'],
    };
}

export function V1AccountToJSON(value?: V1Account | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'accountName': value.accountName,
    };
}

