/* tslint:disable */
/* eslint-disable */
/**
 * go_load/v1/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1Account } from './V1Account';
import {
    V1AccountFromJSON,
    V1AccountFromJSONTyped,
    V1AccountToJSON,
} from './V1Account';

/**
 * 
 * @export
 * @interface V1CreateSessionResponse
 */
export interface V1CreateSessionResponse {
    /**
     * 
     * @type {V1Account}
     * @memberof V1CreateSessionResponse
     */
    account?: V1Account;
}

/**
 * Check if a given object implements the V1CreateSessionResponse interface.
 */
export function instanceOfV1CreateSessionResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1CreateSessionResponseFromJSON(json: any): V1CreateSessionResponse {
    return V1CreateSessionResponseFromJSONTyped(json, false);
}

export function V1CreateSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateSessionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'account': !exists(json, 'account') ? undefined : V1AccountFromJSON(json['account']),
    };
}

export function V1CreateSessionResponseToJSON(value?: V1CreateSessionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'account': V1AccountToJSON(value.account),
    };
}

