/* tslint:disable */
/* eslint-disable */
/**
 * go_load/v1/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1CreateSessionRequest
 */
export interface V1CreateSessionRequest {
    /**
     * 
     * @type {string}
     * @memberof V1CreateSessionRequest
     */
    accountName?: string;
    /**
     * 
     * @type {string}
     * @memberof V1CreateSessionRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the V1CreateSessionRequest interface.
 */
export function instanceOfV1CreateSessionRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1CreateSessionRequestFromJSON(json: any): V1CreateSessionRequest {
    return V1CreateSessionRequestFromJSONTyped(json, false);
}

export function V1CreateSessionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateSessionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountName': !exists(json, 'accountName') ? undefined : json['accountName'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function V1CreateSessionRequestToJSON(value?: V1CreateSessionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountName': value.accountName,
        'password': value.password,
    };
}

