/* tslint:disable */
/* eslint-disable */
/**
 * go_load/v1/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const V1DownloadStatus = {
    Unspecified: 'DOWNLOAD_STATUS_UNSPECIFIED',
    Pending: 'DOWNLOAD_STATUS_PENDING',
    Downloading: 'DOWNLOAD_STATUS_DOWNLOADING',
    Failed: 'DOWNLOAD_STATUS_FAILED',
    Success: 'DOWNLOAD_STATUS_SUCCESS'
} as const;
export type V1DownloadStatus = typeof V1DownloadStatus[keyof typeof V1DownloadStatus];


export function V1DownloadStatusFromJSON(json: any): V1DownloadStatus {
    return V1DownloadStatusFromJSONTyped(json, false);
}

export function V1DownloadStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DownloadStatus {
    return json as V1DownloadStatus;
}

export function V1DownloadStatusToJSON(value?: V1DownloadStatus | null): any {
    return value as any;
}

