/* tslint:disable */
/* eslint-disable */
/**
 * go_load/v1/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const V1DownloadType = {
    Unspecified: 'DOWNLOAD_TYPE_UNSPECIFIED',
    Http: 'DOWNLOAD_TYPE_HTTP'
} as const;
export type V1DownloadType = typeof V1DownloadType[keyof typeof V1DownloadType];


export function V1DownloadTypeFromJSON(json: any): V1DownloadType {
    return V1DownloadTypeFromJSONTyped(json, false);
}

export function V1DownloadTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DownloadType {
    return json as V1DownloadType;
}

export function V1DownloadTypeToJSON(value?: V1DownloadType | null): any {
    return value as any;
}

