/* tslint:disable */
/* eslint-disable */
/**
 * go_load/v1/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1GetDownloadTaskFileRequest
 */
export interface V1GetDownloadTaskFileRequest {
    /**
     * 
     * @type {string}
     * @memberof V1GetDownloadTaskFileRequest
     */
    downloadTaskId?: string;
}

/**
 * Check if a given object implements the V1GetDownloadTaskFileRequest interface.
 */
export function instanceOfV1GetDownloadTaskFileRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1GetDownloadTaskFileRequestFromJSON(json: any): V1GetDownloadTaskFileRequest {
    return V1GetDownloadTaskFileRequestFromJSONTyped(json, false);
}

export function V1GetDownloadTaskFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetDownloadTaskFileRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'downloadTaskId': !exists(json, 'downloadTaskId') ? undefined : json['downloadTaskId'],
    };
}

export function V1GetDownloadTaskFileRequestToJSON(value?: V1GetDownloadTaskFileRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'downloadTaskId': value.downloadTaskId,
    };
}

