/* tslint:disable */
/* eslint-disable */
/**
 * go_load/v1/go_load.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1GetDownloadTaskFileResponse
 */
export interface V1GetDownloadTaskFileResponse {
    /**
     * 
     * @type {string}
     * @memberof V1GetDownloadTaskFileResponse
     */
    data?: string;
}

/**
 * Check if a given object implements the V1GetDownloadTaskFileResponse interface.
 */
export function instanceOfV1GetDownloadTaskFileResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1GetDownloadTaskFileResponseFromJSON(json: any): V1GetDownloadTaskFileResponse {
    return V1GetDownloadTaskFileResponseFromJSONTyped(json, false);
}

export function V1GetDownloadTaskFileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GetDownloadTaskFileResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function V1GetDownloadTaskFileResponseToJSON(value?: V1GetDownloadTaskFileResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
    };
}

